version: "3.8"
services:
  backend:
    networks:
      - app

    build:
      context: ./backend
      dockerfile: Dockerfile

    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: admin
      DB_USERNAME: root
      DB_PASSWORD: root

    depends_on:
      - db

    ports:
      - 8000:8000
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3001:3000

    volumes:
      - ./frontend:/app
    depends_on:
      - backend

    networks:
      - app

  db:
    networks:
      - app

    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33066:3306

networks:
  app:
    driver: bridge
